# Generated by Django 4.2.27 on 2025-12-27 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_gestao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='email',
        ),
        migrations.AddField(
            model_name='plano',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='endereco',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plano',
            name='nome',
            field=models.CharField(choices=[('ESSENCIAL', 'Ultramed Essencial'), ('MASTER', 'Ultramed Master Familiar'), ('EMPRESARIAL', 'Ultramed Empresarial')], max_length=50),
        ),
        migrations.AlterField(
            model_name='plano',
            name='valor_mensal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PAGO', 'Adimplente (Pago)'), ('PENDENTE', 'Pendente'), ('ATRASADO', 'Inadimplente (Atrasado)'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=10)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_gestao.paciente')),
            ],
        ),
    ]
