# Generated by Django 4.2.27 on 2025-12-27 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_gestao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fatura',
            old_name='descricao',
            new_name='linha_digitavel',
        ),
        migrations.AddField(
            model_name='fatura',
            name='link_boleto',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atendimento', models.DateTimeField(auto_now_add=True)),
                ('evolucao', models.TextField()),
                ('prescricao', models.TextField(blank=True, null=True)),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_gestao.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_exame', models.CharField(max_length=255)),
                ('data_solicitacao', models.DateField(auto_now_add=True)),
                ('laudo', models.TextField(blank=True, null=True)),
                ('realizado', models.BooleanField(default=False)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_gestao.paciente')),
            ],
        ),
    ]
