# Generated by Django 4.2.27 on 2025-12-27 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_gestao', '0002_rename_descricao_fatura_linha_digitavel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='endereco',
        ),
        migrations.AddField(
            model_name='paciente',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependentes', to='core_gestao.paciente'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='status',
            field=models.CharField(choices=[('PAGO', 'Pago'), ('PENDENTE', 'Pendente'), ('ATRASADO', 'Atrasado')], default='PENDENTE', max_length=10),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1),
        ),
    ]
