# Generated by Django 4.2.27 on 2025-12-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_gestao', '0004_paciente_bairro_paciente_cidade_paciente_endereco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='possui_dependentes',
            field=models.BooleanField(default=False),
        ),
    ]
