# Generated by Django 4.2.27 on 2026-01-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_gestao', '0005_paciente_possui_dependentes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plano',
            old_name='valor_mensal',
            new_name='valor_anual',
        ),
        migrations.AddField(
            model_name='exame',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='exame',
            name='valor_tabela',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
