# Generated by Django 4.2.27 on 2026-01-06 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_gestao', '0006_rename_valor_mensal_plano_valor_anual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fatura',
            name='linha_digitavel',
        ),
        migrations.RemoveField(
            model_name='fatura',
            name='link_boleto',
        ),
        migrations.AddField(
            model_name='fatura',
            name='metodo_pagamento',
            field=models.CharField(blank=True, choices=[('PIX', 'PIX'), ('CARTAO', 'Cartão de Crédito')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='data_vencimento',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('tipo', models.CharField(choices=[('CONSULTA', 'Consulta'), ('EXAME', 'Exame')], default='CONSULTA', max_length=10)),
                ('status', models.CharField(choices=[('AGENDADO', 'Agendado'), ('CHEGOU', 'Em Espera (Chegou)'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='AGENDADO', max_length=15)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_gestao.paciente')),
            ],
        ),
    ]
