# Generated by Django 4.2.27 on 2026-01-20 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_gestao', '0007_remove_fatura_linha_digitavel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='is_cronico',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('hash_digital', models.CharField(blank=True, max_length=100, null=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='core_gestao.paciente')),
            ],
        ),
    ]
