# Generated by Django 4.2.27 on 2026-01-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_gestao', '0008_paciente_is_cronico_receita'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='doencas_cronicas',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
