# Generated by Django 4.2.27 on 2026-01-20 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_gestao', '0009_paciente_doencas_cronicas'),
    ]

    operations = [
        migrations.AddField(
            model_name='exame',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='exames/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exames_paciente', to='core_gestao.paciente'),
        ),
    ]
