# Generated by Django 4.2.28 on 2026-02-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_gestao', '0011_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='mercadopago_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='is_titular',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='data_vencimento',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='Pagamento',
        ),
    ]
