# Generated by Django 4.2.28 on 2026-04-05 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_gestao', '0012_fatura_mercadopago_id_paciente_is_titular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatura',
            name='mercadopago_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='metodo_pagamento',
            field=models.CharField(blank=True, choices=[('PIX', 'PIX'), ('CARTAO', 'Cartão de Crédito'), ('PIX/CARTAO', 'PIX ou Cartão')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='core_gestao.paciente'),
        ),
    ]
