# Generated by Django 4.2.30 on 2026-08-07 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_gestao', '0014_fatura_plano'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChamadaPainel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_nome', models.CharField(max_length=255)),
                ('consultorio', models.CharField(default='Consultório 1', max_length=80)),
                ('mensagem', models.CharField(default='Sua consulta vai começar', max_length=255)),
                ('chamada_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_gestao.paciente')),
            ],
        ),
    ]
