# 1. Definição do motor Ultramed (Django)
upstream web_app {
    server web:8000;
}

# 2. Redirecionamento Global HTTP -> HTTPS
server {
    listen 80;
    server_name ultramedsaudexingu.com.br rinancode.com.br;
    return 301 https://$host$request_uri;
}

# 3. BLOCO EXCLUSIVO: RINAN TEAM (SaaS Global)
# Este bloco responde APENAS pelo seu domínio novo
server {
    listen 443 ssl;
    server_name rinancode.com.br;

    ssl_certificate /etc/nginx/ssl/live/ultramedsaudexingu.com.br/fullchain.pem; 
    ssl_certificate_key /etc/nginx/ssl/live/ultramedsaudexingu.com.br/privkey.pem;

    # Manda TUDO desse domínio para o Rinan Team na porta 9000
    location / {
        proxy_pass http://172.17.0.1:9000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Garante que o /rinanteam/ também funcione
    location /rinanteam/ {
        proxy_pass http://172.17.0.1:9000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# 4. BLOCO EXCLUSIVO: ULTRAMED (Django)
# Este bloco responde APENAS pelo domínio da Ultramed
server {
    listen 443 ssl;
    server_name ultramedsaudexingu.com.br;

    ssl_certificate /etc/nginx/ssl/live/ultramedsaudexingu.com.br/fullchain.pem; 
    ssl_certificate_key /etc/nginx/ssl/live/ultramedsaudexingu.com.br/privkey.pem;

    location /static/ {
        alias /usr/share/nginx/html/static/;
    }

    location / {
        proxy_pass http://web_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}