# 1. Definição do motor Ultramed (Django)
upstream web_app {
    server web:8000;
}

# 2. Redirecionamento Global HTTP -> HTTPS
server {
    listen 80;
    server_name ultramedsaudexingu.com.br rinancode.com.br;
    return 301 https://$host$request_uri;
}

# 3. BLOCO EXCLUSIVO: RINAN TEAM (SaaS Global)
server {
    listen 443 ssl;
    server_name rinancode.com.br;

    # Certificados SSL
    ssl_certificate /etc/nginx/ssl/live/ultramedsaudexingu.com.br/fullchain.pem; 
    ssl_certificate_key /etc/nginx/ssl/live/ultramedsaudexingu.com.br/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    client_max_body_size 20M;

    location / {
        # USANDO O GATEWAY PADRÃO DO DOCKER (172.17.0.1)
        # É a ponte mais estável para o Nginx achar a porta 9000 da VPS
        proxy_pass http://172.17.0.1:9000/; 
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        
        proxy_connect_timeout 60s;
        proxy_read_timeout 60s;
    }
}

# 4. BLOCO EXCLUSIVO: ULTRAMED (Django)
server {
    listen 443 ssl;
    server_name ultramedsaudexingu.com.br;

    ssl_certificate /etc/nginx/ssl/live/ultramedsaudexingu.com.br/fullchain.pem; 
    ssl_certificate_key /etc/nginx/ssl/live/ultramedsaudexingu.com.br/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    location /static/ {
        alias /usr/share/nginx/html/static/;
    }

    location / {
        proxy_pass http://web_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}