# 1. Definição do motor Ultramed (Django)
upstream web_app {
    server web:8000;
}

# 2. Redirecionamento Global HTTP -> HTTPS
server {
    listen 80;
    server_name ultramedsaudexingu.com.br rinancode.com.br;
    return 301 https://$host$request_uri;
}

# 3. BLOCO EXCLUSIVO: RINAN TEAM (SaaS Global)
server {
    listen 443 ssl;
    server_name rinancode.com.br;

    # Padronizado para o volume /etc/letsencrypt que mapeamos no compose
    ssl_certificate /etc/letsencrypt/live/rinancode.com.br/fullchain.pem; 
    ssl_certificate_key /etc/letsencrypt/live/rinancode.com.br/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    client_max_body_size 20M;

    location / {
        # CORREÇÃO: Usa o host.docker.internal para sair do container e achar o Rinan na porta 9000
        proxy_pass http://host.docker.internal:9000; 
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        
        proxy_connect_timeout 60s;
        proxy_read_timeout 60s;
    }
}

# 4. BLOCO EXCLUSIVO: ULTRAMED (Django)
server {
    listen 443 ssl;
    server_name ultramedsaudexingu.com.br;

    # Padronizado para o caminho interno do container que mapeia o letsencrypt
    ssl_certificate /etc/letsencrypt/live/ultramedsaudexingu.com.br/fullchain.pem; 
    ssl_certificate_key /etc/letsencrypt/live/ultramedsaudexingu.com.br/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    client_max_body_size 20M;

    location /static/ {
        alias /usr/share/nginx/html/static/;
    }

    location /media/ {
        alias /usr/share/nginx/html/media/;
    }

    location / {
        proxy_pass http://web_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}