# Generated by Django 5.0 on 2025-12-15 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_interno', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
