# Generated by Django 5.0 on 2025-12-19 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_interno', '0003_paciente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Assinante', 'verbose_name_plural': 'Assinantes'},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['-data_cadastro'], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='client',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sistema_interno.paciente', verbose_name='Paciente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cidade',
            field=models.CharField(default='São Félix do Xingu', max_length=100),
        ),
        migrations.AddField(
            model_name='paciente',
            name='convenio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Plano ou Particular'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Alergias/Observações'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'Medico'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Médico'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='procedure_name',
            field=models.CharField(max_length=255, verbose_name='Procedimento/Exame'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('AGENDADO', 'Agendado'), ('REALIZADO', 'Realizado'), ('CANCELADO', 'Cancelado'), ('FALTOU', 'Faltou')], default='AGENDADO', max_length=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='group_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Grupo/Empresa'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_interno.cliente'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='issue_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plano',
            name='max_people',
            field=models.IntegerField(default=1, verbose_name='Limite de Pessoas'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='plan_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('FAMILIAR', 'Familiar'), ('CORPORATIVO', 'Corporativo')], default='INDIVIDUAL', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, help_text='Ex: Master, Medico, Colaborador, Cliente', max_length=50, null=True),
        ),
    ]
