# Generated by Django 5.0 on 2025-12-20 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_interno', '0004_alter_cliente_options_alter_paciente_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('preco_base', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='LeadCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=20)),
                ('interesse', models.CharField(blank=True, max_length=255, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['user__username'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='rg',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sistema_interno.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'Medico'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Médico/Doutor'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações/Histórico'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='procedure_name',
            field=models.CharField(max_length=255, verbose_name='Exame/Procedimento'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('AGENDADO', 'Agendado'), ('REALIZADO', 'Realizado'), ('CANCELADO', 'Cancelado')], default='AGENDADO', max_length=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='group_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Grupo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Plano Ativo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Vinculado'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_interno.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='due_date',
            field=models.DateField(verbose_name='Data de Vencimento'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Pago'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='issue_date',
            field=models.DateField(auto_now_add=True, verbose_name='Data de Emissão'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='convenio',
            field=models.CharField(default='PARTICULAR', max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='plano',
            name='max_people',
            field=models.IntegerField(default=1, verbose_name='Limite Máximo de Pessoas'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='plan_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('FAMILIAR', 'Familiar'), ('CORPORATIVO', 'Corporativo')], default='INDIVIDUAL', max_length=15, verbose_name='Tipo de Plano'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
