# Generated by Django 5.0 on 2025-12-20 23:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_interno', '0005_exame_leadcapture_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exame',
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='plano',
            options={},
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='client',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='procedure_name',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='group_name',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendamento',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='medico',
            field=models.CharField(default='Geral', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendamento',
            name='paciente_nome',
            field=models.CharField(default='Paciente Antigo', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando'), ('REALIZADO', 'Realizado'), ('CANCELADO', 'Cancelado')], default='AGUARDANDO', max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistema_interno.plano'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_interno.cliente'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='issue_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='plano',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='plano',
            name='max_people',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='plano',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='plano',
            name='plan_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('FAMILIAR', 'Familiar'), ('CORPORATIVO', 'Corporativo')], default='INDIVIDUAL', max_length=15),
        ),
        migrations.AlterField(
            model_name='plano',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
