# Generated by Django 5.0 on 2025-12-20 23:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_interno', '0006_delete_exame_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fatura',
            name='client',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='exame_nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='tipo',
            field=models.CharField(choices=[('CONSULTA', 'Consulta'), ('EXAME', 'Exame')], default='CONSULTA', max_length=20),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='valor_consulta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fatura',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fatura',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema_interno.paciente'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='paciente_nome_avulso',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fatura',
            name='tipo_pagamento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
