# Generated by Django 5.0 on 2025-12-26 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_interno', '0008_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
    ]
